
service: changeseats

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "arn:aws:s3:::*"
      Action:
        - "s3:*"

functions:
  sekigae:
    handler: handler.handler
    events:
      - http:
          path: changeseats
          method: get
          cors: true
resources:
  Resources:
    sekigae:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: changeseats
